
File: D:\Users\jbb\github\KCT\Kerbal_Construction_Time\..\KerbalConstructionTime.173.version missing
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  

 using System.Reflection;

 [assembly: AssemblyVersion("1.0.0.0")]
